### ISSUE TITLE
Installing DentalSegmentator in Slicer

### ISSUE THREAD

**Issue by Mr-Yellow** [gaudot/SlicerDentalSegmentator#1]
Hi, it seems to be stuck and failed during installing nnunetv2.  The log are shown below.
![image](https://github.com/gaudot/SlicerDentalSegmentator/assets/32990829/8bc1c204-45ff-459c-a202-9efd1a84d8c5)
![image](https://github.com/gaudot/SlicerDentalSegmentator/assets/32990829/39314619-17c9-4a16-8b61-872e829b2e96)
I am new to Slicer, and what should I do to fix this problem !

**Comment by Thibault-Pelletier** [comment]
Hi @Mr-Yellow;

Thank you for reporting this issue. 
Could you give more context on where you encounter this issue (ie: which version of Slicer are you trying to run the module one, which OS) ?

The warnings seem to indicate HTTPs errors which could point to internet access restrictions on your network.

You may need to contact your system administrator to unlock Python "pip install" commands over the network or switch to another network access to install the dependencies.

**Comment by drhamidhmd** [comment]
hello,
i was trying dental segmentator since yesterday but its not working... Slicer version 5.7 preview

**Comment by Thibault-Pelletier** [comment]
Hi @drhamidhmd,

Thank you for testing out our module.
Could you provide us with the following information so that we have a clearer view on what went wrong : 

- Which OS did you try the module on
- Which preview version date did you try it on. Slicer previews are built nightly and we made several fixes to the extension since it was added to the extension manager and you may want to test on the latest preview release to check if the problem is still there.
- What is your machine configuration (RAM / CPU / GPU config)
- Could you give us the information available in the module log. The logs are accessible by clicking on the (i) button next to the apply button
- Could you give us the information available in the Python console 

Thanks in advance.
