### ISSUE TITLE
Fail to load segmentation

### ISSUE THREAD

**Issue by nguyetun5** [gaudot/SlicerDentalSegmentator#10]
I'm using Slicer 5.7.0 revision 32900 6-16-2024 on Windows.  The error code reads as fail to load segmentation.  I can get it to work on my Mac with M1 or M2 but can get the extension to work on Windows.

**Comment by Thibault-Pelletier** [comment]
Hi @nguyetun5 ,

Thank you for your interest in our extension and reaching out.
Could you provide the inference logs when you experience your error on Windows?

Please also note that there is a known error with SimpleITK on Windows in the current preview builds (see here : https://github.com/Slicer/Slicer/issues/7799).
SimpleITK is required when using this extension.

**Comment by nguyetun5** [comment]
Here’s the screen capture of the log error[A screenshot of a computer program  Description automatically generated]

Tung

From: Thibault-Pelletier ***@***.***>
Date: Tuesday, June 18, 2024 at 1:09 AM
To: gaudot/SlicerDentalSegmentator ***@***.***>
Cc: nguyetun5 ***@***.***>, Mention ***@***.***>
Subject: Re: [gaudot/SlicerDentalSegmentator] Fail to load segmentation (Issue #10)

Hi @nguyetun5<https://github.com/nguyetun5> ,

Thank you for your interest in our extension and reaching out.
Could you provide the inference logs when you experience your error on Windows?

Please also note that there is a known error with SimpleITK on Windows in the current preview builds (see here : Slicer/Slicer#7799<https://github.com/Slicer/Slicer/issues/7799>).
SimpleITK is required when using this extension.

**Comment by Thibault-Pelletier** [comment]
Hi @nguyetun5,

Your screenshot was lost in the email response.
Could you answer directly on the Github issue page?

**Comment by DanielLim7** [comment]
I'm experiencing the same issue on Windows. After inputting the CBCT data and running the "Apply" command, I encounter the following error:
"
Failed to load the segmentation.
Something went wrong during the nnUNet processing.
Please check the logs for potential errors and contact the library maintainers."

Additionally, I see the following message on the screen:

"QtWebEngineProcess.exe - System Error
The code execution cannot proceed because Qt5Core.DLL was not found. Reinstalling the program may fix the problem."

However, I tried reinstalling the program, but the issue persists. I'm not sure if the following critical message is relevant, but I noted it down:

Critical Message:
"TIFFReadDirectory: Warning, Unknown field with tag 50839 (0xc697) encountered."

"void __cdecl qMRMLSegmentEditorWidget::setSourceVolumeNode(class vtkMRMLNode *) failed: need to set segment editor and segmentation nodes first."

**Comment by Thibault-Pelletier** [comment]
Hi @DanielLim7,

Thank you for your interest and reaching out to us.
I'm not sure the errors you noted down are related to your problem.

- Which OS and version of 3D Slicer are you running the extension on?
- Do you experience the problem even when selecting "cpu" device ?
- Do you experience the problem on every data including Slicer's CBCTDentalSurgery sample?
- Could you provide the informations present by clicking on the (i) icon next to the "Apply" button after you have experienced the problem?
- Would you be able to share the anonymized data on which you have the problem for us to investigate further? 

Best,
Thibault

**Comment by DanielLim7** [comment]
Hi @Thibault-Pelletier, after reinstalling 3D Slicer, it worked.

**Comment by DanielLim7** [comment]
Hi @Thibault-Pelletier, who can I contact if I have private questions about the program?

**Comment by DanielLim7** [comment]
@Thibault-Pelletier Where can I find the email to ask you the questions?

**Comment by DanielLim7** [comment]
@Thibault-Pelletier @GauthierDot I wanted to follow up on the message I sent last week. Could you send me the email if you've had the chance to look at it?

**Comment by Thibault-Pelletier** [comment]
Hi @DanielLim7, on Kitware's side, you can address your question to julien.finet@kitware.com
